literals.literal_type.*:
  type: config_entity
  label: 'Literal type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    kind:
      type: string
      label: 'Kind'
      constraints:
        PluginExists:
          manager: plugin.manager.literal_kind
          interface: '\Drupal\literals\LiteralKindInterface'
    validate_as:
      type: string
      label: 'Validate as'

views.filter.literal_audience:
  type: views.filter.in_operator
  label: 'Literal audience'
